// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteRecipeApiRecipesRecipeIdDelete, extractRecipeApiRecipesExtractPost, getJobApiJobsJobIdGet, getRecipeApiRecipesRecipeIdGet, getRecipeImageApiRecipesRecipeIdImageGet, getSpendApiSpendGet, healthApiHealthGet, listJobsApiJobsGet, listRecipesApiRecipesGet, type Options, patchRecipeApiRecipesRecipeIdPatch, uploadRecipeVideoApiRecipesUploadPost } from '../sdk.gen';
import type { DeleteRecipeApiRecipesRecipeIdDeleteData, DeleteRecipeApiRecipesRecipeIdDeleteError, DeleteRecipeApiRecipesRecipeIdDeleteResponse, ExtractRecipeApiRecipesExtractPostData, ExtractRecipeApiRecipesExtractPostError, ExtractRecipeApiRecipesExtractPostResponse, GetJobApiJobsJobIdGetData, GetJobApiJobsJobIdGetError, GetJobApiJobsJobIdGetResponse, GetRecipeApiRecipesRecipeIdGetData, GetRecipeApiRecipesRecipeIdGetError, GetRecipeApiRecipesRecipeIdGetResponse, GetRecipeImageApiRecipesRecipeIdImageGetData, GetRecipeImageApiRecipesRecipeIdImageGetError, GetSpendApiSpendGetData, GetSpendApiSpendGetError, GetSpendApiSpendGetResponse, HealthApiHealthGetData, HealthApiHealthGetResponse, ListJobsApiJobsGetData, ListJobsApiJobsGetError, ListJobsApiJobsGetResponse, ListRecipesApiRecipesGetData, ListRecipesApiRecipesGetError, ListRecipesApiRecipesGetResponse, PatchRecipeApiRecipesRecipeIdPatchData, PatchRecipeApiRecipesRecipeIdPatchError, PatchRecipeApiRecipesRecipeIdPatchResponse, UploadRecipeVideoApiRecipesUploadPostData, UploadRecipeVideoApiRecipesUploadPostError, UploadRecipeVideoApiRecipesUploadPostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthApiHealthGetQueryKey = (options?: Options<HealthApiHealthGetData>) => createQueryKey('healthApiHealthGet', options);

/**
 * Health
 *
 * Health check. NOT publicly exempt from auth — it exposes spend/cookie
 * state (plan §16 amendment 3).
 */
export const healthApiHealthGetOptions = (options?: Options<HealthApiHealthGetData>) => queryOptions<HealthApiHealthGetResponse, DefaultError, HealthApiHealthGetResponse, ReturnType<typeof healthApiHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthApiHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthApiHealthGetQueryKey(options)
});

export const listJobsApiJobsGetQueryKey = (options?: Options<ListJobsApiJobsGetData>) => createQueryKey('listJobsApiJobsGet', options);

/**
 * List Jobs
 *
 * The jobs drawer (active + recent), newest activity first.
 */
export const listJobsApiJobsGetOptions = (options?: Options<ListJobsApiJobsGetData>) => queryOptions<ListJobsApiJobsGetResponse, ListJobsApiJobsGetError, ListJobsApiJobsGetResponse, ReturnType<typeof listJobsApiJobsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listJobsApiJobsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listJobsApiJobsGetQueryKey(options)
});

export const getJobApiJobsJobIdGetQueryKey = (options: Options<GetJobApiJobsJobIdGetData>) => createQueryKey('getJobApiJobsJobIdGet', options);

/**
 * Get Job
 */
export const getJobApiJobsJobIdGetOptions = (options: Options<GetJobApiJobsJobIdGetData>) => queryOptions<GetJobApiJobsJobIdGetResponse, GetJobApiJobsJobIdGetError, GetJobApiJobsJobIdGetResponse, ReturnType<typeof getJobApiJobsJobIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobApiJobsJobIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobApiJobsJobIdGetQueryKey(options)
});

export const listRecipesApiRecipesGetQueryKey = (options?: Options<ListRecipesApiRecipesGetData>) => createQueryKey('listRecipesApiRecipesGet', options);

/**
 * List Recipes
 */
export const listRecipesApiRecipesGetOptions = (options?: Options<ListRecipesApiRecipesGetData>) => queryOptions<ListRecipesApiRecipesGetResponse, ListRecipesApiRecipesGetError, ListRecipesApiRecipesGetResponse, ReturnType<typeof listRecipesApiRecipesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRecipesApiRecipesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRecipesApiRecipesGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listRecipesApiRecipesGetInfiniteQueryKey = (options?: Options<ListRecipesApiRecipesGetData>): QueryKey<Options<ListRecipesApiRecipesGetData>> => createQueryKey('listRecipesApiRecipesGet', options, true);

/**
 * List Recipes
 */
export const listRecipesApiRecipesGetInfiniteOptions = (options?: Options<ListRecipesApiRecipesGetData>) => {
    const opts = infiniteQueryOptions<ListRecipesApiRecipesGetResponse, ListRecipesApiRecipesGetError, InfiniteData<ListRecipesApiRecipesGetResponse>, QueryKey<Options<ListRecipesApiRecipesGetData>>, number | Pick<QueryKey<Options<ListRecipesApiRecipesGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListRecipesApiRecipesGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listRecipesApiRecipesGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listRecipesApiRecipesGetInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Extract Recipe
 */
export const extractRecipeApiRecipesExtractPostMutation = (options?: Partial<Options<ExtractRecipeApiRecipesExtractPostData>>): UseMutationOptions<ExtractRecipeApiRecipesExtractPostResponse, ExtractRecipeApiRecipesExtractPostError, Options<ExtractRecipeApiRecipesExtractPostData>> => {
    const mutationOptions: UseMutationOptions<ExtractRecipeApiRecipesExtractPostResponse, ExtractRecipeApiRecipesExtractPostError, Options<ExtractRecipeApiRecipesExtractPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await extractRecipeApiRecipesExtractPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload Recipe Video
 *
 * The §16.10 tier-2 floor: manual save + upload. Same job contract; the
 * content-addressed canonical id means re-uploading the same bytes dedupes
 * exactly like a re-pasted URL.
 */
export const uploadRecipeVideoApiRecipesUploadPostMutation = (options?: Partial<Options<UploadRecipeVideoApiRecipesUploadPostData>>): UseMutationOptions<UploadRecipeVideoApiRecipesUploadPostResponse, UploadRecipeVideoApiRecipesUploadPostError, Options<UploadRecipeVideoApiRecipesUploadPostData>> => {
    const mutationOptions: UseMutationOptions<UploadRecipeVideoApiRecipesUploadPostResponse, UploadRecipeVideoApiRecipesUploadPostError, Options<UploadRecipeVideoApiRecipesUploadPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadRecipeVideoApiRecipesUploadPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Recipe
 */
export const deleteRecipeApiRecipesRecipeIdDeleteMutation = (options?: Partial<Options<DeleteRecipeApiRecipesRecipeIdDeleteData>>): UseMutationOptions<DeleteRecipeApiRecipesRecipeIdDeleteResponse, DeleteRecipeApiRecipesRecipeIdDeleteError, Options<DeleteRecipeApiRecipesRecipeIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteRecipeApiRecipesRecipeIdDeleteResponse, DeleteRecipeApiRecipesRecipeIdDeleteError, Options<DeleteRecipeApiRecipesRecipeIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRecipeApiRecipesRecipeIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRecipeApiRecipesRecipeIdGetQueryKey = (options: Options<GetRecipeApiRecipesRecipeIdGetData>) => createQueryKey('getRecipeApiRecipesRecipeIdGet', options);

/**
 * Get Recipe
 */
export const getRecipeApiRecipesRecipeIdGetOptions = (options: Options<GetRecipeApiRecipesRecipeIdGetData>) => queryOptions<GetRecipeApiRecipesRecipeIdGetResponse, GetRecipeApiRecipesRecipeIdGetError, GetRecipeApiRecipesRecipeIdGetResponse, ReturnType<typeof getRecipeApiRecipesRecipeIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipeApiRecipesRecipeIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipeApiRecipesRecipeIdGetQueryKey(options)
});

/**
 * Patch Recipe
 */
export const patchRecipeApiRecipesRecipeIdPatchMutation = (options?: Partial<Options<PatchRecipeApiRecipesRecipeIdPatchData>>): UseMutationOptions<PatchRecipeApiRecipesRecipeIdPatchResponse, PatchRecipeApiRecipesRecipeIdPatchError, Options<PatchRecipeApiRecipesRecipeIdPatchData>> => {
    const mutationOptions: UseMutationOptions<PatchRecipeApiRecipesRecipeIdPatchResponse, PatchRecipeApiRecipesRecipeIdPatchError, Options<PatchRecipeApiRecipesRecipeIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchRecipeApiRecipesRecipeIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRecipeImageApiRecipesRecipeIdImageGetQueryKey = (options: Options<GetRecipeImageApiRecipesRecipeIdImageGetData>) => createQueryKey('getRecipeImageApiRecipesRecipeIdImageGet', options);

/**
 * Get Recipe Image
 *
 * Stream the generated illustration. One 404 covers every miss — no
 * recipe, no illustration generated yet, file gone from the archive.
 */
export const getRecipeImageApiRecipesRecipeIdImageGetOptions = (options: Options<GetRecipeImageApiRecipesRecipeIdImageGetData>) => queryOptions<unknown, GetRecipeImageApiRecipesRecipeIdImageGetError, unknown, ReturnType<typeof getRecipeImageApiRecipesRecipeIdImageGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipeImageApiRecipesRecipeIdImageGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipeImageApiRecipesRecipeIdImageGetQueryKey(options)
});

export const getSpendApiSpendGetQueryKey = (options?: Options<GetSpendApiSpendGetData>) => createQueryKey('getSpendApiSpendGet', options);

/**
 * Get Spend
 *
 * Per-day, per-model spend over the last ``days`` UTC days, plus
 * month-to-date and the configured caps (null caps = fail-closed config).
 */
export const getSpendApiSpendGetOptions = (options?: Options<GetSpendApiSpendGetData>) => queryOptions<GetSpendApiSpendGetResponse, GetSpendApiSpendGetError, GetSpendApiSpendGetResponse, ReturnType<typeof getSpendApiSpendGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSpendApiSpendGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSpendApiSpendGetQueryKey(options)
});
