// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteRecipeApiRecipesRecipeIdDeleteData, DeleteRecipeApiRecipesRecipeIdDeleteErrors, DeleteRecipeApiRecipesRecipeIdDeleteResponses, ExtractRecipeApiRecipesExtractPostData, ExtractRecipeApiRecipesExtractPostErrors, ExtractRecipeApiRecipesExtractPostResponses, GetJobApiJobsJobIdGetData, GetJobApiJobsJobIdGetErrors, GetJobApiJobsJobIdGetResponses, GetRecipeApiRecipesRecipeIdGetData, GetRecipeApiRecipesRecipeIdGetErrors, GetRecipeApiRecipesRecipeIdGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, ListRecipesApiRecipesGetData, ListRecipesApiRecipesGetErrors, ListRecipesApiRecipesGetResponses, PatchRecipeApiRecipesRecipeIdPatchData, PatchRecipeApiRecipesRecipeIdPatchErrors, PatchRecipeApiRecipesRecipeIdPatchResponses, UploadRecipeVideoApiRecipesUploadPostData, UploadRecipeVideoApiRecipesUploadPostErrors, UploadRecipeVideoApiRecipesUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 *
 * Health check. NOT publicly exempt from auth — it exposes spend/cookie
 * state (plan §16 amendment 3).
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>): RequestResult<HealthApiHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/health',
    ...options
});

/**
 * Get Job
 */
export const getJobApiJobsJobIdGet = <ThrowOnError extends boolean = false>(options: Options<GetJobApiJobsJobIdGetData, ThrowOnError>): RequestResult<GetJobApiJobsJobIdGetResponses, GetJobApiJobsJobIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetJobApiJobsJobIdGetResponses, GetJobApiJobsJobIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/jobs/{job_id}',
    ...options
});

/**
 * List Recipes
 */
export const listRecipesApiRecipesGet = <ThrowOnError extends boolean = false>(options?: Options<ListRecipesApiRecipesGetData, ThrowOnError>): RequestResult<ListRecipesApiRecipesGetResponses, ListRecipesApiRecipesGetErrors, ThrowOnError> => (options?.client ?? client).get<ListRecipesApiRecipesGetResponses, ListRecipesApiRecipesGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes',
    ...options
});

/**
 * Extract Recipe
 */
export const extractRecipeApiRecipesExtractPost = <ThrowOnError extends boolean = false>(options: Options<ExtractRecipeApiRecipesExtractPostData, ThrowOnError>): RequestResult<ExtractRecipeApiRecipesExtractPostResponses, ExtractRecipeApiRecipesExtractPostErrors, ThrowOnError> => (options.client ?? client).post<ExtractRecipeApiRecipesExtractPostResponses, ExtractRecipeApiRecipesExtractPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes/extract',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Recipe Video
 *
 * The §16.10 tier-2 floor: manual save + upload. Same job contract; the
 * content-addressed canonical id means re-uploading the same bytes dedupes
 * exactly like a re-pasted URL.
 */
export const uploadRecipeVideoApiRecipesUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadRecipeVideoApiRecipesUploadPostData, ThrowOnError>): RequestResult<UploadRecipeVideoApiRecipesUploadPostResponses, UploadRecipeVideoApiRecipesUploadPostErrors, ThrowOnError> => (options.client ?? client).post<UploadRecipeVideoApiRecipesUploadPostResponses, UploadRecipeVideoApiRecipesUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Recipe
 */
export const deleteRecipeApiRecipesRecipeIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRecipeApiRecipesRecipeIdDeleteData, ThrowOnError>): RequestResult<DeleteRecipeApiRecipesRecipeIdDeleteResponses, DeleteRecipeApiRecipesRecipeIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRecipeApiRecipesRecipeIdDeleteResponses, DeleteRecipeApiRecipesRecipeIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes/{recipe_id}',
    ...options
});

/**
 * Get Recipe
 */
export const getRecipeApiRecipesRecipeIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRecipeApiRecipesRecipeIdGetData, ThrowOnError>): RequestResult<GetRecipeApiRecipesRecipeIdGetResponses, GetRecipeApiRecipesRecipeIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetRecipeApiRecipesRecipeIdGetResponses, GetRecipeApiRecipesRecipeIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes/{recipe_id}',
    ...options
});

/**
 * Patch Recipe
 */
export const patchRecipeApiRecipesRecipeIdPatch = <ThrowOnError extends boolean = false>(options: Options<PatchRecipeApiRecipesRecipeIdPatchData, ThrowOnError>): RequestResult<PatchRecipeApiRecipesRecipeIdPatchResponses, PatchRecipeApiRecipesRecipeIdPatchErrors, ThrowOnError> => (options.client ?? client).patch<PatchRecipeApiRecipesRecipeIdPatchResponses, PatchRecipeApiRecipesRecipeIdPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/recipes/{recipe_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
