// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_recipe_video_api_recipes_upload_post
 */
export type BodyUploadRecipeVideoApiRecipesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Platform Hint
     */
    platform_hint?: string | null;
    /**
     * Provenance Url
     */
    provenance_url?: string | null;
};

/**
 * ErrorBody
 *
 * Typed error payload: ``error_type`` is the stable taxonomy string the
 * UI maps onto actions (runbook link, retry button, hard stop).
 */
export type ErrorBody = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Error Type
     */
    error_type: string;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Phase-4 health shape (plan §7 screen 4): sidecar + cookie + backup
 * staleness + spend readout, plus which extractor/model is live. New fields
 * keep schema-level defaults so the generated TS client treats them as
 * optional — the endpoint always sets them explicitly.
 */
export type HealthResponse = {
    /**
     * Attempts Today
     */
    attempts_today?: number | null;
    /**
     * Backup
     */
    backup?: 'fresh' | 'stale' | 'not_configured';
    /**
     * Backup Finished At
     */
    backup_finished_at?: string | null;
    /**
     * Budget Is Personal
     */
    budget_is_personal?: boolean;
    /**
     * Budget Monthly Usd
     */
    budget_monthly_usd?: number | null;
    /**
     * Cookie Freshness
     */
    cookie_freshness?: 'fresh' | 'aging' | 'stale' | 'not_configured';
    /**
     * Cookie Set Date
     */
    cookie_set_date?: string | null;
    /**
     * Daily Attempt Cap
     */
    daily_attempt_cap?: number | null;
    /**
     * Db
     */
    db: 'ok' | 'unreachable';
    /**
     * Extractor
     */
    extractor?: string;
    /**
     * Model
     */
    model?: string;
    /**
     * Paid Tier
     */
    paid_tier?: boolean;
    /**
     * Sentry Enabled
     */
    sentry_enabled?: boolean;
    /**
     * Sidecar
     */
    sidecar?: 'ok' | 'unreachable' | 'not_configured';
    /**
     * Spend Month Usd
     */
    spend_month_usd?: number | null;
    /**
     * Status
     */
    status: 'ok' | 'degraded';
    /**
     * Worker
     */
    worker?: 'alive' | 'dead' | 'not_running';
};

/**
 * InviteCreate
 *
 * POST /api/admin/invites body. Lightweight email shape check (a friends-
 * invite flow, not a validation fortress) — normalization happens server-side.
 */
export type InviteCreate = {
    /**
     * Email
     */
    email: string;
};

/**
 * InviteList
 */
export type InviteList = {
    /**
     * Items
     */
    items: Array<InviteOut>;
};

/**
 * InviteOut
 *
 * An invite as the admin sees it — NEVER the token_hash. ``dev_activation_
 * link`` is present ONLY when chefclaw_email='fake' (the real link is emailed).
 */
export type InviteOut = {
    /**
     * Accepted At
     */
    accepted_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Dev Activation Link
     */
    dev_activation_link?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * InvitePublicOut
 *
 * GET /api/invites/{token} — the public invite-accept shape (M13). ``status``
 * is 'pending' | 'invalid'; ``email`` is revealed ONLY for a live pending
 * invite (a missing/expired/revoked token is a uniform 'invalid', no email).
 */
export type InvitePublicOut = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Canonical Id
     */
    canonical_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Error Type
     */
    error_type: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Recipe Ids
     */
    recipe_ids?: Array<string>;
    /**
     * Result Recipe Ids
     */
    result_recipe_ids: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * MeOut
 *
 * GET /api/me — the authenticated identity. ``id`` is the owner_id the
 * service scopes on; ``is_admin`` gates admin-UI visibility only (server-
 * derived, never a writable field — critique M9).
 */
export type MeOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Name
     */
    name: string;
};

/**
 * RecipeDetail
 *
 * Full recipe including the (read-only) document.
 */
export type RecipeDetail = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Dish Index
     */
    dish_index: number;
    /**
     * Document
     */
    document: {
        [key: string]: unknown;
    };
    /**
     * Estimated Difficulty Level
     */
    estimated_difficulty_level?: number | null;
    /**
     * Estimated Source
     */
    estimated_source?: 'derived' | 'user' | null;
    /**
     * Estimated Spiciness Level
     */
    estimated_spiciness_level?: number | null;
    /**
     * Extraction Meta
     */
    extraction_meta: {
        [key: string]: unknown;
    };
    /**
     * Has Image
     */
    has_image?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Ingredient Count
     */
    ingredient_count?: number | null;
    /**
     * Platform
     */
    platform: string;
    /**
     * Source Url
     */
    source_url: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Title En
     */
    title_en: string | null;
    /**
     * Title Original
     */
    title_original: string | null;
    /**
     * Total Time Minutes
     */
    total_time_minutes?: number | null;
    /**
     * User Notes
     */
    user_notes: string | null;
};

/**
 * RecipePage
 */
export type RecipePage = {
    /**
     * Items
     */
    items: Array<RecipeSummary>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * RecipePatch
 *
 * The user-editable fields. extra='forbid' rejects document edits.
 *
 * ``tags`` / ``user_notes`` are free metadata; the two ``estimated_*`` fields
 * let the owner CORRECT the derived 0–3 estimates (a provided value re-flags
 * the ``estimated`` column ``source="user"``, taking precedence over the
 * model's derivation — see ``services.recipes.patch_recipe``). All are
 * optional; only fields actually present in the body are applied
 * (``model_fields_set``), so an explicit ``null`` clears while an absent field
 * is untouched. ``strict=True`` on the estimate ints blocks bool→int coercion
 * (``True`` is not ``spiciness_level=1``) — the same guard the document schema
 * keeps.
 */
export type RecipePatch = {
    /**
     * Estimated Difficulty Level
     */
    estimated_difficulty_level?: number | null;
    /**
     * Estimated Spiciness Level
     */
    estimated_spiciness_level?: number | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * User Notes
     */
    user_notes?: string | null;
};

/**
 * RecipeSummary
 *
 * Library-card shape (list endpoint). ``difficulty`` /
 * ``total_time_minutes`` are lifted VERBATIM from the stored validated
 * document; ``ingredient_count`` is the length of its ingredients list — a
 * structural count, not a food quantity (Hard Rule 7 governs food data like
 * amounts/weights, which stay verbatim inside the document). ``has_image``
 * derives from the server-side ``image_url`` (the generated illustration
 * path), which itself never leaves the API (the /image endpoint streams the
 * file). ``estimated_spiciness_level`` / ``estimated_difficulty_level`` are
 * the 0–3 estimates projected from the separate ``estimated`` column (never
 * inside the verbatim document); ``estimated_source`` says whether they are the
 * model's ``"derived"`` guess (flag 'estimated' in the UI) or an owner
 * ``"user"`` correction.
 */
export type RecipeSummary = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Dish Index
     */
    dish_index: number;
    /**
     * Estimated Difficulty Level
     */
    estimated_difficulty_level?: number | null;
    /**
     * Estimated Source
     */
    estimated_source?: 'derived' | 'user' | null;
    /**
     * Estimated Spiciness Level
     */
    estimated_spiciness_level?: number | null;
    /**
     * Has Image
     */
    has_image?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Ingredient Count
     */
    ingredient_count?: number | null;
    /**
     * Platform
     */
    platform: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Title En
     */
    title_en: string | null;
    /**
     * Title Original
     */
    title_original: string | null;
    /**
     * Total Time Minutes
     */
    total_time_minutes?: number | null;
};

/**
 * SpendDay
 *
 * One UTC day of ledger activity; days with zero attempts are omitted.
 */
export type SpendDay = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Date
     */
    date: string;
    /**
     * Models
     */
    models: Array<SpendModelSlice>;
};

/**
 * SpendModelSlice
 *
 * One model's share of a day's ledger (GET /api/spend, V2-A ADR).
 */
export type SpendModelSlice = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Model
     */
    model: string;
    /**
     * Tokens In
     */
    tokens_in: number;
    /**
     * Tokens Out
     */
    tokens_out: number;
    /**
     * Tokens Thinking
     */
    tokens_thinking: number;
};

/**
 * SpendSummaryOut
 *
 * The spend readout: per-day/per-model history over the requested window
 * plus month-to-date and the configured caps. ``budget_monthly_usd`` /
 * ``daily_attempt_cap`` are null when the budget config is fail-closed —
 * the UI must say 'extraction disabled', never invent a cap.
 */
export type SpendSummaryOut = {
    /**
     * Attempts Today
     */
    attempts_today: number;
    /**
     * Budget Monthly Usd
     */
    budget_monthly_usd?: number | null;
    /**
     * Daily Attempt Cap
     */
    daily_attempt_cap?: number | null;
    /**
     * Days
     */
    days: Array<SpendDay>;
    /**
     * Month To Date Usd
     */
    month_to_date_usd: number;
    /**
     * Period Days
     */
    period_days: number;
    /**
     * Total Usd
     */
    total_usd: number;
};

/**
 * UserBudgetOut
 *
 * A user's per-user cost controls after the write. ``null`` on a cap means
 * no per-user override (the global env cap applies); ``paid_tier`` false means
 * the global GEMINI_MODEL (free) default.
 */
export type UserBudgetOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Max Attempts Per Day
     */
    max_attempts_per_day?: number | null;
    /**
     * Monthly Budget Usd
     */
    monthly_budget_usd?: number | null;
    /**
     * Paid Tier
     */
    paid_tier?: boolean;
};

/**
 * UserBudgetPatch
 *
 * PATCH /api/admin/users/{user_id}/budget body (M3 per-user cost controls).
 * All fields optional — a PARTIAL update keyed on which fields the request
 * sends: a field PRESENT sets it, a cap PRESENT+``null`` CLEARS it (the
 * account falls back to the global env cap), ABSENT leaves it unchanged.
 * Positive caps only — 0/negative is a 422 (use ``null`` to clear). The router
 * reads ``model_fields_set`` to tell 'clear' from 'leave alone'.
 *
 * ``paid_tier`` toggles this account onto the paid Gemini model
 * (GEMINI_PAID_MODEL) for its extractions — it is not a cap, so ``null`` is
 * not accepted; send true/false.
 */
export type UserBudgetPatch = {
    /**
     * Max Attempts Per Day
     */
    max_attempts_per_day?: number | null;
    /**
     * Monthly Budget Usd
     */
    monthly_budget_usd?: number | null;
    /**
     * Paid Tier
     */
    paid_tier?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListInvitesApiAdminInvitesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/admin/invites';
};

export type ListInvitesApiAdminInvitesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitesApiAdminInvitesGetError = ListInvitesApiAdminInvitesGetErrors[keyof ListInvitesApiAdminInvitesGetErrors];

export type ListInvitesApiAdminInvitesGetResponses = {
    /**
     * Successful Response
     */
    200: InviteList;
};

export type ListInvitesApiAdminInvitesGetResponse = ListInvitesApiAdminInvitesGetResponses[keyof ListInvitesApiAdminInvitesGetResponses];

export type CreateInviteApiAdminInvitesPostData = {
    body: InviteCreate;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type CreateInviteApiAdminInvitesPostErrors = {
    /**
     * Conflict
     */
    409: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorBody;
    /**
     * Service Unavailable
     */
    503: ErrorBody;
};

export type CreateInviteApiAdminInvitesPostError = CreateInviteApiAdminInvitesPostErrors[keyof CreateInviteApiAdminInvitesPostErrors];

export type CreateInviteApiAdminInvitesPostResponses = {
    /**
     * OK
     */
    200: InviteOut;
    /**
     * Successful Response
     */
    201: InviteOut;
};

export type CreateInviteApiAdminInvitesPostResponse = CreateInviteApiAdminInvitesPostResponses[keyof CreateInviteApiAdminInvitesPostResponses];

export type RevokeInviteApiAdminInvitesInviteIdRevokePostData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/admin/invites/{invite_id}/revoke';
};

export type RevokeInviteApiAdminInvitesInviteIdRevokePostErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Conflict
     */
    409: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteApiAdminInvitesInviteIdRevokePostError = RevokeInviteApiAdminInvitesInviteIdRevokePostErrors[keyof RevokeInviteApiAdminInvitesInviteIdRevokePostErrors];

export type RevokeInviteApiAdminInvitesInviteIdRevokePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateUserBudgetApiAdminUsersUserIdBudgetPatchData = {
    body: UserBudgetPatch;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/budget';
};

export type UpdateUserBudgetApiAdminUsersUserIdBudgetPatchErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserBudgetApiAdminUsersUserIdBudgetPatchError = UpdateUserBudgetApiAdminUsersUserIdBudgetPatchErrors[keyof UpdateUserBudgetApiAdminUsersUserIdBudgetPatchErrors];

export type UpdateUserBudgetApiAdminUsersUserIdBudgetPatchResponses = {
    /**
     * Successful Response
     */
    200: UserBudgetOut;
};

export type UpdateUserBudgetApiAdminUsersUserIdBudgetPatchResponse = UpdateUserBudgetApiAdminUsersUserIdBudgetPatchResponses[keyof UpdateUserBudgetApiAdminUsersUserIdBudgetPatchResponses];

export type GoogleCallbackApiAuthGoogleCallbackGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Code
         */
        code?: string;
        /**
         * State
         */
        state?: string;
    };
    url: '/api/auth/google/callback';
};

export type GoogleCallbackApiAuthGoogleCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleCallbackApiAuthGoogleCallbackGetError = GoogleCallbackApiAuthGoogleCallbackGetErrors[keyof GoogleCallbackApiAuthGoogleCallbackGetErrors];

export type GoogleCallbackApiAuthGoogleCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GoogleLoginApiAuthGoogleLoginGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Next
         */
        next?: string;
    };
    url: '/api/auth/google/login';
};

export type GoogleLoginApiAuthGoogleLoginGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleLoginApiAuthGoogleLoginGetError = GoogleLoginApiAuthGoogleLoginGetErrors[keyof GoogleLoginApiAuthGoogleLoginGetErrors];

export type GoogleLoginApiAuthGoogleLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type PublicInviteApiInvitesTokenGetData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/invites/{token}';
};

export type PublicInviteApiInvitesTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicInviteApiInvitesTokenGetError = PublicInviteApiInvitesTokenGetErrors[keyof PublicInviteApiInvitesTokenGetErrors];

export type PublicInviteApiInvitesTokenGetResponses = {
    /**
     * Successful Response
     */
    200: InvitePublicOut;
};

export type PublicInviteApiInvitesTokenGetResponse = PublicInviteApiInvitesTokenGetResponses[keyof PublicInviteApiInvitesTokenGetResponses];

export type ListJobsApiJobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/jobs';
};

export type ListJobsApiJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsApiJobsGetError = ListJobsApiJobsGetErrors[keyof ListJobsApiJobsGetErrors];

export type ListJobsApiJobsGetResponses = {
    /**
     * Response List Jobs Api Jobs Get
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsApiJobsGetResponse = ListJobsApiJobsGetResponses[keyof ListJobsApiJobsGetResponses];

export type GetJobApiJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobApiJobsJobIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobApiJobsJobIdGetError = GetJobApiJobsJobIdGetErrors[keyof GetJobApiJobsJobIdGetErrors];

export type GetJobApiJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobApiJobsJobIdGetResponse = GetJobApiJobsJobIdGetResponses[keyof GetJobApiJobsJobIdGetResponses];

export type MeApiMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeApiMeGetResponses = {
    /**
     * Successful Response
     */
    200: MeOut;
};

export type MeApiMeGetResponse = MeApiMeGetResponses[keyof MeApiMeGetResponses];

export type ListRecipesApiRecipesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Platform
         */
        platform?: string | null;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Sort
         */
        sort?: 'newest' | 'oldest';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/recipes';
};

export type ListRecipesApiRecipesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecipesApiRecipesGetError = ListRecipesApiRecipesGetErrors[keyof ListRecipesApiRecipesGetErrors];

export type ListRecipesApiRecipesGetResponses = {
    /**
     * Successful Response
     */
    200: RecipePage;
};

export type ListRecipesApiRecipesGetResponse = ListRecipesApiRecipesGetResponses[keyof ListRecipesApiRecipesGetResponses];

export type ExtractRecipeApiRecipesExtractPostData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/recipes/extract';
};

export type ExtractRecipeApiRecipesExtractPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorBody;
    /**
     * Service Unavailable
     */
    503: ErrorBody;
};

export type ExtractRecipeApiRecipesExtractPostError = ExtractRecipeApiRecipesExtractPostErrors[keyof ExtractRecipeApiRecipesExtractPostErrors];

export type ExtractRecipeApiRecipesExtractPostResponses = {
    /**
     * Existing job (canonical dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type ExtractRecipeApiRecipesExtractPostResponse = ExtractRecipeApiRecipesExtractPostResponses[keyof ExtractRecipeApiRecipesExtractPostResponses];

export type UploadRecipeVideoApiRecipesUploadPostData = {
    body: BodyUploadRecipeVideoApiRecipesUploadPost;
    path?: never;
    query?: never;
    url: '/api/recipes/upload';
};

export type UploadRecipeVideoApiRecipesUploadPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Content Too Large
     */
    413: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorBody;
    /**
     * Service Unavailable
     */
    503: ErrorBody;
};

export type UploadRecipeVideoApiRecipesUploadPostError = UploadRecipeVideoApiRecipesUploadPostErrors[keyof UploadRecipeVideoApiRecipesUploadPostErrors];

export type UploadRecipeVideoApiRecipesUploadPostResponses = {
    /**
     * Existing job (canonical dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type UploadRecipeVideoApiRecipesUploadPostResponse = UploadRecipeVideoApiRecipesUploadPostResponses[keyof UploadRecipeVideoApiRecipesUploadPostResponses];

export type DeleteRecipeApiRecipesRecipeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type DeleteRecipeApiRecipesRecipeIdDeleteErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRecipeApiRecipesRecipeIdDeleteError = DeleteRecipeApiRecipesRecipeIdDeleteErrors[keyof DeleteRecipeApiRecipesRecipeIdDeleteErrors];

export type DeleteRecipeApiRecipesRecipeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRecipeApiRecipesRecipeIdDeleteResponse = DeleteRecipeApiRecipesRecipeIdDeleteResponses[keyof DeleteRecipeApiRecipesRecipeIdDeleteResponses];

export type GetRecipeApiRecipesRecipeIdGetData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type GetRecipeApiRecipesRecipeIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipeApiRecipesRecipeIdGetError = GetRecipeApiRecipesRecipeIdGetErrors[keyof GetRecipeApiRecipesRecipeIdGetErrors];

export type GetRecipeApiRecipesRecipeIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecipeDetail;
};

export type GetRecipeApiRecipesRecipeIdGetResponse = GetRecipeApiRecipesRecipeIdGetResponses[keyof GetRecipeApiRecipesRecipeIdGetResponses];

export type PatchRecipeApiRecipesRecipeIdPatchData = {
    body: RecipePatch;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type PatchRecipeApiRecipesRecipeIdPatchErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchRecipeApiRecipesRecipeIdPatchError = PatchRecipeApiRecipesRecipeIdPatchErrors[keyof PatchRecipeApiRecipesRecipeIdPatchErrors];

export type PatchRecipeApiRecipesRecipeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RecipeDetail;
};

export type PatchRecipeApiRecipesRecipeIdPatchResponse = PatchRecipeApiRecipesRecipeIdPatchResponses[keyof PatchRecipeApiRecipesRecipeIdPatchResponses];

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}/illustration';
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostError = RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors[keyof RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors];

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses = {
    /**
     * Existing active illustration job (dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponse = RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses[keyof RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses];

export type GetRecipeImageApiRecipesRecipeIdImageGetData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}/image';
};

export type GetRecipeImageApiRecipesRecipeIdImageGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipeImageApiRecipesRecipeIdImageGetError = GetRecipeImageApiRecipesRecipeIdImageGetErrors[keyof GetRecipeImageApiRecipesRecipeIdImageGetErrors];

export type GetRecipeImageApiRecipesRecipeIdImageGetResponses = {
    /**
     * The recipe's generated illustration.
     */
    200: unknown;
};

export type GetSpendApiSpendGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/spend';
};

export type GetSpendApiSpendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSpendApiSpendGetError = GetSpendApiSpendGetErrors[keyof GetSpendApiSpendGetErrors];

export type GetSpendApiSpendGetResponses = {
    /**
     * Successful Response
     */
    200: SpendSummaryOut;
};

export type GetSpendApiSpendGetResponse = GetSpendApiSpendGetResponses[keyof GetSpendApiSpendGetResponses];
