// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_recipe_video_api_recipes_upload_post
 */
export type BodyUploadRecipeVideoApiRecipesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Platform Hint
     */
    platform_hint?: string | null;
    /**
     * Provenance Url
     */
    provenance_url?: string | null;
};

/**
 * ErrorBody
 *
 * Typed error payload: ``error_type`` is the stable taxonomy string the
 * UI maps onto actions (runbook link, retry button, hard stop).
 */
export type ErrorBody = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Error Type
     */
    error_type: string;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Phase-4 health shape (plan §7 screen 4): sidecar + cookie + backup
 * staleness + spend readout, plus which extractor/model is live. New fields
 * keep schema-level defaults so the generated TS client treats them as
 * optional — the endpoint always sets them explicitly.
 */
export type HealthResponse = {
    /**
     * Attempts Today
     */
    attempts_today?: number | null;
    /**
     * Backup
     */
    backup?: 'fresh' | 'stale' | 'not_configured';
    /**
     * Backup Finished At
     */
    backup_finished_at?: string | null;
    /**
     * Budget Monthly Usd
     */
    budget_monthly_usd?: number | null;
    /**
     * Cookie Freshness
     */
    cookie_freshness?: 'fresh' | 'aging' | 'stale' | 'not_configured';
    /**
     * Cookie Set Date
     */
    cookie_set_date?: string | null;
    /**
     * Daily Attempt Cap
     */
    daily_attempt_cap?: number | null;
    /**
     * Db
     */
    db: 'ok' | 'unreachable';
    /**
     * Extractor
     */
    extractor?: string;
    /**
     * Model
     */
    model?: string;
    /**
     * Sentry Enabled
     */
    sentry_enabled?: boolean;
    /**
     * Sidecar
     */
    sidecar?: 'ok' | 'unreachable' | 'not_configured';
    /**
     * Spend Month Usd
     */
    spend_month_usd?: number | null;
    /**
     * Status
     */
    status: 'ok' | 'degraded';
    /**
     * Worker
     */
    worker?: 'alive' | 'dead' | 'not_running';
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Canonical Id
     */
    canonical_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Error Type
     */
    error_type: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Recipe Ids
     */
    recipe_ids?: Array<string>;
    /**
     * Result Recipe Ids
     */
    result_recipe_ids: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * RecipeDetail
 *
 * Full recipe including the (read-only) document.
 */
export type RecipeDetail = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Dish Index
     */
    dish_index: number;
    /**
     * Document
     */
    document: {
        [key: string]: unknown;
    };
    /**
     * Estimated Difficulty Level
     */
    estimated_difficulty_level?: number | null;
    /**
     * Estimated Spiciness Level
     */
    estimated_spiciness_level?: number | null;
    /**
     * Extraction Meta
     */
    extraction_meta: {
        [key: string]: unknown;
    };
    /**
     * Has Image
     */
    has_image?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Ingredient Count
     */
    ingredient_count?: number | null;
    /**
     * Platform
     */
    platform: string;
    /**
     * Source Url
     */
    source_url: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Title En
     */
    title_en: string | null;
    /**
     * Title Original
     */
    title_original: string | null;
    /**
     * Total Time Minutes
     */
    total_time_minutes?: number | null;
    /**
     * User Notes
     */
    user_notes: string | null;
};

/**
 * RecipePage
 */
export type RecipePage = {
    /**
     * Items
     */
    items: Array<RecipeSummary>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * RecipePatch
 *
 * The ONLY user-editable fields. extra='forbid' rejects document edits.
 */
export type RecipePatch = {
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * User Notes
     */
    user_notes?: string | null;
};

/**
 * RecipeSummary
 *
 * Library-card shape (list endpoint). ``difficulty`` /
 * ``total_time_minutes`` are lifted VERBATIM from the stored validated
 * document; ``ingredient_count`` is the length of its ingredients list — a
 * structural count, not a food quantity (Hard Rule 7 governs food data like
 * amounts/weights, which stay verbatim inside the document). ``has_image``
 * derives from the server-side ``image_url`` (the generated illustration
 * path), which itself never leaves the API (the /image endpoint streams the
 * file). ``estimated_spiciness_level`` / ``estimated_difficulty_level`` are
 * the DERIVED estimates projected from the separate ``estimated`` column —
 * flagged 'estimated' in the UI, never inside the verbatim document.
 */
export type RecipeSummary = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Dish Index
     */
    dish_index: number;
    /**
     * Estimated Difficulty Level
     */
    estimated_difficulty_level?: number | null;
    /**
     * Estimated Spiciness Level
     */
    estimated_spiciness_level?: number | null;
    /**
     * Has Image
     */
    has_image?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Ingredient Count
     */
    ingredient_count?: number | null;
    /**
     * Platform
     */
    platform: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Title En
     */
    title_en: string | null;
    /**
     * Title Original
     */
    title_original: string | null;
    /**
     * Total Time Minutes
     */
    total_time_minutes?: number | null;
};

/**
 * SpendDay
 *
 * One UTC day of ledger activity; days with zero attempts are omitted.
 */
export type SpendDay = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Date
     */
    date: string;
    /**
     * Models
     */
    models: Array<SpendModelSlice>;
};

/**
 * SpendModelSlice
 *
 * One model's share of a day's ledger (GET /api/spend, V2-A ADR).
 */
export type SpendModelSlice = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Model
     */
    model: string;
    /**
     * Tokens In
     */
    tokens_in: number;
    /**
     * Tokens Out
     */
    tokens_out: number;
    /**
     * Tokens Thinking
     */
    tokens_thinking: number;
};

/**
 * SpendSummaryOut
 *
 * The spend readout: per-day/per-model history over the requested window
 * plus month-to-date and the configured caps. ``budget_monthly_usd`` /
 * ``daily_attempt_cap`` are null when the budget config is fail-closed —
 * the UI must say 'extraction disabled', never invent a cap.
 */
export type SpendSummaryOut = {
    /**
     * Attempts Today
     */
    attempts_today: number;
    /**
     * Budget Monthly Usd
     */
    budget_monthly_usd?: number | null;
    /**
     * Daily Attempt Cap
     */
    daily_attempt_cap?: number | null;
    /**
     * Days
     */
    days: Array<SpendDay>;
    /**
     * Month To Date Usd
     */
    month_to_date_usd: number;
    /**
     * Period Days
     */
    period_days: number;
    /**
     * Total Usd
     */
    total_usd: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type ListJobsApiJobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/jobs';
};

export type ListJobsApiJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsApiJobsGetError = ListJobsApiJobsGetErrors[keyof ListJobsApiJobsGetErrors];

export type ListJobsApiJobsGetResponses = {
    /**
     * Response List Jobs Api Jobs Get
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsApiJobsGetResponse = ListJobsApiJobsGetResponses[keyof ListJobsApiJobsGetResponses];

export type GetJobApiJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobApiJobsJobIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobApiJobsJobIdGetError = GetJobApiJobsJobIdGetErrors[keyof GetJobApiJobsJobIdGetErrors];

export type GetJobApiJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobApiJobsJobIdGetResponse = GetJobApiJobsJobIdGetResponses[keyof GetJobApiJobsJobIdGetResponses];

export type ListRecipesApiRecipesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Platform
         */
        platform?: string | null;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Sort
         */
        sort?: 'newest' | 'oldest';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/recipes';
};

export type ListRecipesApiRecipesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecipesApiRecipesGetError = ListRecipesApiRecipesGetErrors[keyof ListRecipesApiRecipesGetErrors];

export type ListRecipesApiRecipesGetResponses = {
    /**
     * Successful Response
     */
    200: RecipePage;
};

export type ListRecipesApiRecipesGetResponse = ListRecipesApiRecipesGetResponses[keyof ListRecipesApiRecipesGetResponses];

export type ExtractRecipeApiRecipesExtractPostData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/recipes/extract';
};

export type ExtractRecipeApiRecipesExtractPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorBody;
    /**
     * Service Unavailable
     */
    503: ErrorBody;
};

export type ExtractRecipeApiRecipesExtractPostError = ExtractRecipeApiRecipesExtractPostErrors[keyof ExtractRecipeApiRecipesExtractPostErrors];

export type ExtractRecipeApiRecipesExtractPostResponses = {
    /**
     * Existing job (canonical dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type ExtractRecipeApiRecipesExtractPostResponse = ExtractRecipeApiRecipesExtractPostResponses[keyof ExtractRecipeApiRecipesExtractPostResponses];

export type UploadRecipeVideoApiRecipesUploadPostData = {
    body: BodyUploadRecipeVideoApiRecipesUploadPost;
    path?: never;
    query?: never;
    url: '/api/recipes/upload';
};

export type UploadRecipeVideoApiRecipesUploadPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Content Too Large
     */
    413: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorBody;
    /**
     * Service Unavailable
     */
    503: ErrorBody;
};

export type UploadRecipeVideoApiRecipesUploadPostError = UploadRecipeVideoApiRecipesUploadPostErrors[keyof UploadRecipeVideoApiRecipesUploadPostErrors];

export type UploadRecipeVideoApiRecipesUploadPostResponses = {
    /**
     * Existing job (canonical dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type UploadRecipeVideoApiRecipesUploadPostResponse = UploadRecipeVideoApiRecipesUploadPostResponses[keyof UploadRecipeVideoApiRecipesUploadPostResponses];

export type DeleteRecipeApiRecipesRecipeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type DeleteRecipeApiRecipesRecipeIdDeleteErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRecipeApiRecipesRecipeIdDeleteError = DeleteRecipeApiRecipesRecipeIdDeleteErrors[keyof DeleteRecipeApiRecipesRecipeIdDeleteErrors];

export type DeleteRecipeApiRecipesRecipeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRecipeApiRecipesRecipeIdDeleteResponse = DeleteRecipeApiRecipesRecipeIdDeleteResponses[keyof DeleteRecipeApiRecipesRecipeIdDeleteResponses];

export type GetRecipeApiRecipesRecipeIdGetData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type GetRecipeApiRecipesRecipeIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipeApiRecipesRecipeIdGetError = GetRecipeApiRecipesRecipeIdGetErrors[keyof GetRecipeApiRecipesRecipeIdGetErrors];

export type GetRecipeApiRecipesRecipeIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecipeDetail;
};

export type GetRecipeApiRecipesRecipeIdGetResponse = GetRecipeApiRecipesRecipeIdGetResponses[keyof GetRecipeApiRecipesRecipeIdGetResponses];

export type PatchRecipeApiRecipesRecipeIdPatchData = {
    body: RecipePatch;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}';
};

export type PatchRecipeApiRecipesRecipeIdPatchErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchRecipeApiRecipesRecipeIdPatchError = PatchRecipeApiRecipesRecipeIdPatchErrors[keyof PatchRecipeApiRecipesRecipeIdPatchErrors];

export type PatchRecipeApiRecipesRecipeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RecipeDetail;
};

export type PatchRecipeApiRecipesRecipeIdPatchResponse = PatchRecipeApiRecipesRecipeIdPatchResponses[keyof PatchRecipeApiRecipesRecipeIdPatchResponses];

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}/illustration';
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostError = RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors[keyof RegenerateIllustrationApiRecipesRecipeIdIllustrationPostErrors];

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses = {
    /**
     * Existing active illustration job (dedupe hit)
     */
    200: JobOut;
    /**
     * Successful Response
     */
    202: JobOut;
};

export type RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponse = RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses[keyof RegenerateIllustrationApiRecipesRecipeIdIllustrationPostResponses];

export type GetRecipeImageApiRecipesRecipeIdImageGetData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/recipes/{recipe_id}/image';
};

export type GetRecipeImageApiRecipesRecipeIdImageGetErrors = {
    /**
     * Not Found
     */
    404: ErrorBody;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipeImageApiRecipesRecipeIdImageGetError = GetRecipeImageApiRecipesRecipeIdImageGetErrors[keyof GetRecipeImageApiRecipesRecipeIdImageGetErrors];

export type GetRecipeImageApiRecipesRecipeIdImageGetResponses = {
    /**
     * The recipe's generated illustration.
     */
    200: unknown;
};

export type GetSpendApiSpendGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/spend';
};

export type GetSpendApiSpendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSpendApiSpendGetError = GetSpendApiSpendGetErrors[keyof GetSpendApiSpendGetErrors];

export type GetSpendApiSpendGetResponses = {
    /**
     * Successful Response
     */
    200: SpendSummaryOut;
};

export type GetSpendApiSpendGetResponse = GetSpendApiSpendGetResponses[keyof GetSpendApiSpendGetResponses];
